Repository department-of-veterans-affairs/notification-api, pull requests merged in 2022-12, with the labels that each got.

#977 860 Update API Docs: Notification Endpoint
  documents/openapi/openapi.yaml
Labels: Tech Debt

#973 #482: Format log message with old printf style
  app/celery/onsite_notification_tasks.py
  app/va/va_onsite/va_onsite_client.py
Labels: Tech Debt, Notify

#958 #935 Missing Status Reasons Updates
  .talismanrc
  app/celery/process_pinpoint_receipt_tasks.py
  app/celery/process_ses_receipts_tasks.py
  tests/app/celery/test_process_ses_receipts_tasks.py
Labels: python, enhancement

#980 #975 Update provider selection logic for e-mail
  lambda_functions/user_flows/test_retrieve_everything.py
Labels: QA

#987 Temporarily Removed Twistlock Scans
  .github/workflows/dev_deploy.yml
  .github/workflows/tag_trigger.yml
Labels: bug

#988 #979 Updated AWS_PINPOINT_APP_ID to use the correct id
  cd/application-deployment/perf/vaec-api-task-definition.json
  cd/application-deployment/perf/vaec-celery-beat-task-definition.json
  cd/application-deployment/perf/vaec-celery-task-definition.json
Labels: bug

#938 Testing pytest failure output
  .talismanrc
  lambda_functions/user_flows/conftest.py
  lambda_functions/user_flows/test_retrieve_everything.py
Labels: Notify, enhancement

#996 Upgrade api requirements
  requirements-app.txt
  requirements.txt
Labels: dependencies, Notify

#1015 Make log levels consistent with the team's definitions. Revise excep
  .talismanrc
  lambda_functions/two_way_sms/two_way_sms_v2.py
Labels: Notify

#1006 #971 Billing: BigQuery - New daily file upload
  .github/workflows/deploy_lambda_dev.yml
  .github/workflows/lambda-functions.yml
  .talismanrc
  app/celery/reporting_tasks.py
  app/config.py
  app/dao/fact_billing_dao.py
  lambda_functions/nightly_billing_bigquery_upload/nightly_billing_stats_upload_lambda.py
  lambda_functions/nightly_billing_bigquery_upload/requirements-lambda.txt
  tests/app/dao/test_ft_billing_dao.py
Labels: enhancement
