Repository department-of-veterans-affairs/notification-api, pull requests merged in 2022-08, with the labels that each got.

#760 #758 Customize Github Actions and Deployments for Notification-API Repo
  .github/release.yaml
  .github/workflows/build-manual.yaml
  .github/workflows/build.yml
  .github/workflows/deployment.yaml
  .github/workflows/deployment.yml
  .github/workflows/dev-ci.yaml
  .github/workflows/dev_deploy.yml
  .github/workflows/lambda-functions.yml
  .github/workflows/perf-build-deploy.yaml
  .github/workflows/production-trigger.yaml
  .github/workflows/release_trigger.yml
  .github/workflows/tag_trigger.yml
  .github/workflows/tagging.yml
  .github/workflows/twistlock.yml
  .github/workflows/user_flows.yml
Labels: enhancement

#794 #793 Allow for Manual Lambda Deployments to Dev
  .github/workflows/deploy_lambda_dev.yml
Labels: devops, actions

#792 #777 Resolve Lambda Timeout Related to Removing Opt-outs
  lambda_functions/va_profile_remove_old_opt_outs/va_profile_remove_old_opt_outs_lambda.py
Labels: Bug, lambda

#775 #166 Dev: Add Roles
  app/models.py
  migrations/versions/0351_user_service_roles.py
  tests/app/conftest.py
  tests/app/test_model.py
Labels: enhancement

#795 Dev output update
  .github/workflows/dev_deploy.yml
  .github/workflows/release_trigger.yml
  .github/workflows/tag_trigger.yml
Labels: devops, actions

#813 #812 explicit timeout vetext forwarder lambda
  lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
  tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
Labels: Bug

#818 554 switch httpclient to requests
  .github/workflows/lambda-functions.yml
  lambda_functions/vetext_incoming_forwarder_lambda/requirements-lambda.txt
  lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
  tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
Labels: hot fix
