Repository department-of-veterans-affairs/notification-api, pull requests merged in 2022-11, with the labels that each got.

#930 #855 Modify the deployment packaging for VA Profile integration lambdas.
  .github/workflows/lambda-functions.yml
  lambda_functions/va_profile/requirements-lambda.txt
  lambda_functions/va_profile_remove_old_opt_outs/requirements-lambda.txt
  lambda_functions/va_profile_remove_old_opt_outs/va_profile_remove_old_opt_outs_lambda.py
Labels: VA Profile, Notify, devops

#937 #934 Remove inaccurate comments from va_profile_opt_in_out_lambda.py
  lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
Labels: Notify

#924 #878 Not supported between instances of NoneType and datetime_datetime
  app/celery/scheduled_tasks.py
  app/models.py
  migrations/versions/0352_updated_at_default.py
  tests/app/dao/test_provider_details_dao.py
Labels: Tech Debt

#943 909-update-aws-actions-to-node16
  .github/workflows/build.yml
  .github/workflows/db-downgrade.yml
  .github/workflows/deployment.yml
  .github/workflows/lambda-functions.yml
  .github/workflows/load-test-email-delivery-time.yaml
  .github/workflows/load-test-sms-response-time.yaml
  .github/workflows/test-github-actions.yml
  .github/workflows/twistlock.yml
  .github/workflows/update-datadog-image.yaml
  .github/workflows/user_flows.yml
Labels: github_actions, Notify, devops

#953 #856 API Doc update - Email Notification Endpoint
  documents/openapi/openapi.yaml
Labels: Tech Debt

#963 #858 Update API Docs: SMS Notification Endpoint
  documents/openapi/openapi.yaml
Labels: Tech Debt

#950 #944 Modify Provider selection logic
  .talismanrc
  app/celery/provider_tasks.py
  app/celery/scheduled_tasks.py
  app/clients/__init__.py
  app/config.py
  app/dao/provider_details_dao.py
  app/dao/templates_dao.py
  app/delivery/send_to_providers.py
  app/notifications/process_notifications.py
  app/notifications/rest.py
  app/provider_details/provider_service.py
  app/provider_details/switch_providers.py
  lambda_functions/user_flows/test_retrieve_everything.py
  tests/app/celery/test_provider_tasks.py
  tests/app/celery/test_scheduled_tasks.py
  tests/app/conftest.py
  tests/app/dao/test_provider_details_dao.py
  tests/app/delivery/test_send_to_providers.py
  tests/app/provider_details/test_provider_service.py
Labels: bug

#972 927 Remove unused folders and files
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .python-version
  CHANGELOG.md
  LICENSE
  SECURITY.md
  runtime.txt
Labels: Tech Debt, Notify
