Repository department-of-veterans-affairs/notification-api, pull requests merged in 2022-10, with the labels that each got.

#852 #836 make va_profile_opt_in_out lambda read certificates from lambda layers and ACM
  lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
  tests/lambda_functions/va_profile/test_va_profile_integration.py
Labels: Notify

#857 Updating requirements
  Makefile
  README.md
  lambda_functions/va_profile/requirements-lambda.txt
  load_testing/requirements.txt
  requirements-app.txt
  requirements.txt
  requirements_for_test.txt
  requirements_for_user_flows.txt
Labels: Notify

#907 #831 Fix BUG: Lambdas Environments not Unique
  .github/workflows/lambda-functions.yml
Labels: bug, Notify

#914 Github actions 'set-output' updated
  .github/workflows/db-downgrade.yml
  .github/workflows/deployment.yml
  .github/workflows/dev_deploy.yml
  .github/workflows/release_trigger.yml
  .github/workflows/tag_trigger.yml
  scripts/tag_git_dev.sh
  scripts/tag_git_staging.sh
Labels: Notify, enhancement

#919 #918 VA Profile integration: KeyError raised when the sourceDate attribute is missing from the POST body
  .talismanrc
  lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
  tests/lambda_functions/va_profile/test_va_profile_integration.py
Labels: bug, VA Profile, Notify

#915 Requirements upgrades after rebuilding the app and test images.
  lambda_functions/va_profile/requirements-lambda.txt
  requirements-app.txt
  requirements.txt
  requirements_for_test.txt
Labels: dependencies, Notify

#908 #844 - Missing Notification Status Reasons. Branch: Bugfix/844
  .talismanrc
  app/celery/letters_pdf_tasks.py
  app/celery/provider_tasks.py
  tests/app/celery/test_letters_pdf_tasks.py
Labels: bug

#921 Github actions 'set-output' updated
  .github/workflows/dev_deploy.yml
  .github/workflows/release_trigger.yml
  .github/workflows/tag_trigger.yml
Labels: enhancement

#926 #925 Changed inputs for if blocks
  .github/workflows/db-downgrade.yml
  .github/workflows/deploy_lambda_dev.yml
  .github/workflows/dev_deploy.yml
  .github/workflows/load-test-email-delivery-time.yaml
  .github/workflows/load-test-sms-response-time.yaml
  .github/workflows/user_flows.yml
Labels: bug, Notify, devops
