Repository department-of-veterans-affairs/notification-api, pull requests merged in 2023-05, with the labels that each got.

#1233 #1122 Profile SMS Path
  application.py
  cd/application-deployment/dev/vaec-api-task-definition.json
  cd/application-deployment/dev/vaec-celery-beat-task-definition.json
  cd/application-deployment/dev/vaec-celery-task-definition.json
  cd/application-deployment/perf/vaec-api-task-definition.json
  cd/application-deployment/perf/vaec-celery-beat-task-definition.json
  cd/application-deployment/perf/vaec-celery-task-definition.json
  cd/application-deployment/prod/vaec-api-task-definition.json
  cd/application-deployment/prod/vaec-celery-beat-task-definition.json
  cd/application-deployment/prod/vaec-celery-task-definition.json
  cd/application-deployment/staging/vaec-api-task-definition.json
  cd/application-deployment/staging/vaec-celery-beat-task-definition.json
  cd/application-deployment/staging/vaec-celery-task-definition.json
  ci/Dockerfile
  requirements-app.txt
  requirements.txt
  scripts/run_app.sh
Labels: devops

#1255 Added 2 CA certificates to certs/ for MPI integration
  .talismanrc
  certs/DigiCert-Global-G2-TLS-RSA-SHA256-2020-CA1.cer
  certs/DigiCert-Global-Root-G2.cer
Labels: MPI, Notify, hotfix

#1256 #1222 Update requirements.txt to use a newer version of notification-utils
  .talismanrc
  requirements.txt
Labels: hotfix

#1264 #1217 Change a logging call from "warning" to "critical"
  app/celery/process_delivery_status_result_tasks.py
  app/celery/process_pinpoint_receipt_tasks.py
Labels: enhancement

#1262 #1198 Upgrade the app image to use Alpine 3.17
  README.md
  ci/Dockerfile
  ci/Dockerfile.local
Labels: docker, QA, enhancement

#1283 #1251 Graceful Shutdown For Celery Tasks
  app/celery/celery.py
  scripts/run_celery.sh
Labels: bug

#1285 #1284 Use Alpine Linux v3.16 for the Docker image
  README.md
  ci/Dockerfile
  ci/Dockerfile.local
Labels: bug, docker, hotfix

#1282 #1270 lambda packaging for nightly stats and VA Profile integration
  .github/workflows/lambda-functions.yml
  lambda_functions/nightly_billing_bigquery_upload/requirements-lambda.txt
  lambda_functions/nightly_stats_bigquery_upload/requirements-lambda.txt
Labels: dependencies, lambda

#1290 #1252 Add the default_send_indicator column to the CommunicationItem table
  app/models.py
  migrations/versions/0358_default_send_field.py
  tests/app/communication_item/test_rest.py
Labels: enhancement

#1291 1277 Implement Celery Serverhooks
  app/celery/celery.py
Labels: enhancement

#1296 970 MPI Read Timeout
  app/va/mpi/mpi.py
Labels: bug
