Repository department-of-veterans-affairs/notification-api, pull requests merged in 2023-03, with the labels that each got.

#1084 #1083 installing datadog into our app
  application.py
  cd/application-deployment/dev/vaec-api-task-definition.json
  cd/application-deployment/dev/vaec-celery-beat-task-definition.json
  cd/application-deployment/dev/vaec-celery-task-definition.json
  cd/application-deployment/perf/vaec-api-task-definition.json
  cd/application-deployment/perf/vaec-celery-beat-task-definition.json
  cd/application-deployment/perf/vaec-celery-task-definition.json
  cd/application-deployment/prod/vaec-api-task-definition.json
  cd/application-deployment/prod/vaec-celery-beat-task-definition.json
  cd/application-deployment/prod/vaec-celery-task-definition.json
  cd/application-deployment/staging/vaec-api-task-definition.json
  cd/application-deployment/staging/vaec-celery-beat-task-definition.json
  cd/application-deployment/staging/vaec-celery-task-definition.json
  requirements-app.txt
  requirements.txt
  requirements_for_test.txt
Labels: devops

#1110 1050 Update nightly billing with cost and msg parts
  app/celery/reporting_tasks.py
  app/dao/fact_billing_dao.py
  lambda_functions/nightly_billing_bigquery_upload/nightly_billing_stats_upload_lambda.py
  tests/app/dao/test_ft_billing_dao.py
  tests/app/db.py
Labels: enhancement

#1129 #1082 Remove User Flows for Perf Deploy
  .github/workflows/dev_deploy.yml
  .github/workflows/user_flows.yml
Labels: github_actions, devops

#1113 #1074 Delivery Status Lambda
  .github/workflows/deploy_lambda_dev.yml
  .github/workflows/lambda-functions.yml
  lambda_functions/delivery_status_processor_lambda/delivery_status_processor_lambda.py
  tests/lambda_functions/delivery_status_processor_lambda/test_delivery_status_processor_lambda.py
Labels: enhancement

#1117 #939 and #1111 VeText 502
  lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
  tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
Labels: bug

#1142 gunicorn Fix for Eventlet
  Makefile
  requirements-app.txt
  requirements.txt
Labels: bug

#1131 855 db migration to create promoted templates table
  app/models.py
  migrations/versions/0357_promoted_templates_table.py
Labels: enhancement

#1118 #1073 twilio sms translate
  app/__init__.py
  app/celery/process_delivery_status_result_tasks.py
  app/clients/sms/__init__.py
  app/clients/sms/twilio.py
  application.py
  lambda_functions/delivery_status_processor_lambda/delivery_status_processor_lambda.py
  tests/app/clients/test_twilio.py
  tests/lambda_functions/delivery_status_processor_lambda/test_delivery_status_processor_lambda.py
  tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
Labels: enhancement

#1184 #1182 twilio delivery status callback url
  app/__init__.py
  app/clients/sms/twilio.py
  tests/app/clients/test_twilio.py
Labels: enhancement

#1190 #1189 BUG: Standard pseudo-random generators are not suitable for security/cryptographic purposes
  app/__init__.py
Labels: bug

#1193 Adjusted Payload Sent in Callbacks to Services' Endpoints
  app/celery/service_callback_tasks.py
  tests/app/celery/test_service_callback_tasks.py
Labels: hotfix
