Repository department-of-veterans-affairs/notification-api, pull requests merged in 2023-09, with the labels that each got.

#1435 Update PR Template
  .github/pull_request_template.md
Labels: devops

#1438 #1360 POST /v3/notifications/ revision
  Makefile
  app/authentication/auth.py
  app/v3/__init__.py
  app/v3/notifications/notification_schemas.py
  app/v3/notifications/rest.py
  documents/openapi/openapi.yaml
  requirements-app.txt
  tests/app/v3/notifications/test_notification_schemas.py
  tests/app/v3/notifications/test_rest.py
Labels: enhancement

#1443 Add p2p_enabled field to services table
  app/models.py
  migrations/versions/0362_add_service_field.py
Labels: enhancement

#1447 Update PR Template
  .github/pull_request_template.md
Labels: devops

#1448 #1326 Run QA Suite on Deploy to Dev action
  .github/workflows/dev_deploy.yml
  .github/workflows/regression-public.yml
Labels: devops

#1450 #886 remove unneeded TODOs
  app/platform_stats/rest.py
Labels: documentation

#1452 #1326 - Run All QA Suite Tests
  .github/workflows/regression-public.yml
Labels: enhancement

#1453 #1390 - upgrading dependencies for pip packages
  Makefile
  requirements-app.txt
  requirements.txt
Labels: dependencies, security

#1456 Deploy to Dev - name change
  .github/workflows/dev_deploy.yml
Labels: devops

#1459 Add Reply-to Inbox Table
  app/models.py
  migrations/versions/0363_add_reply_to_inbox.py
Labels: enhancement

#1463 #1449 - BUG: Pinpoint Successful Status Sent vs Delivered
  app/celery/process_pinpoint_receipt_tasks.py
  app/notifications/aws_sns_status_callback.py
  tests/app/celery/test_process_pinpoint_receipt_tasks.py
Labels: bug

#1465 Swagger corrections
  documents/openapi/openapi.yaml
Labels: Notify, documentation

#1457 #1163 Remove routes and other code for sending a PDF letter.
  app/service/rest.py
  app/service/send_notification.py
  tests/app/service/test_rest.py
  tests/app/service/test_send_pdf_letter_notification.py
Labels: Tech Debt, breaking-change

#1458 #1158 Remove letter-contact routes
  app/service/rest.py
  tests/app/service/test_rest.py
Labels: Tech Debt, breaking-change

#1468 More Swagger corrections
  documents/openapi/openapi.yaml
Labels: Notify, documentation
