Repository department-of-veterans-affairs/notification-api, pull requests merged in 2023-11, with the labels that each got.

#1520 #1322 - Remove User Flows from API
  .github/workflows/deploy_lambda_dev.yml
  .github/workflows/dev_deploy.yml
  .github/workflows/lambda-functions.yml
  .github/workflows/user_flows.yml
  .gitignore
  .talismanrc
  Makefile
  app/provider_details/provider_service.py
  ci/docker-compose-user-flow.yml
  documents/ci cd flow.puml
  lambda_functions/user_flows/conftest.py
  lambda_functions/user_flows/requirements-lambda.txt
  lambda_functions/user_flows/steps.py
  lambda_functions/user_flows/test_retrieve_everything.py
  lambda_functions/user_flows/user_flows_lambda.py
  scripts/run_user_flows.sh
  user_flows/steps.py
  user_flows/test_retrieve_everything.py
Labels: github_actions, lambda

#1522 #1512 notification failures table
  app/models.py
  migrations/versions/0365_add_notification_failures.py
Labels: enhancement

#1532 #1504 - Use the default SMS sender if one is not provided
  app/celery/v3/notification_tasks.py
  tests/app/celery/v3/test_notification_tasks.py
Labels: enhancement

#1528 #1506 Comp and Pen Scheduling Notification Sends
  .talismanrc
  app/celery/process_ses_receipts_tasks.py
  app/celery/scheduled_tasks.py
  app/celery/tasks.py
  app/config.py
  app/feature_flags.py
  app/invite/rest.py
  app/models.py
  app/notifications/process_letter_notifications.py
  app/notifications/process_notifications.py
  app/notifications/rest.py
  app/notifications/send_notifications.py
  app/organisation/invite_rest.py
  app/organisation/rest.py
  app/service/rest.py
  app/service/send_notification.py
  app/service/sender.py
  app/user/rest.py
  app/v2/notifications/post_notifications.py
  cd/application-deployment/dev/vaec-api-task-definition.json
  cd/application-deployment/dev/vaec-celery-beat-task-definition.json
  cd/application-deployment/dev/vaec-celery-task-definition.json
  cd/application-deployment/perf/vaec-api-task-definition.json
  cd/application-deployment/perf/vaec-celery-beat-task-definition.json
  cd/application-deployment/perf/vaec-celery-task-definition.json
  cd/application-deployment/prod/vaec-api-task-definition.json
  cd/application-deployment/prod/vaec-celery-beat-task-definition.json
  cd/application-deployment/prod/vaec-celery-task-definition.json
  cd/application-deployment/staging/vaec-api-task-definition.json
  cd/application-deployment/staging/vaec-celery-beat-task-definition.json
  cd/application-deployment/staging/vaec-celery-task-definition.json
  tests/app/celery/test_scheduled_tasks.py
  tests/app/dao/notification_dao/test_notification_dao.py
  tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
  tests/app/notifications/test_process_notifications.py
  tests/app/notifications/test_send_notifications.py
  tests/app/service/test_send_one_off_notification.py
  tests/app/template/test_rest.py
  tests/app/user/test_rest.py
  tests/app/v2/notifications/test_post_notifications.py
Labels: enhancement

#1540 Fixed Parameter Location for Perf
  cd/application-deployment/perf/vaec-celery-beat-task-definition.json
Labels: hotfix

#1546 Hotfix to ignore Safety vulnerability 61893 (urllib3)
  Makefile
Labels: Notify, hotfix, security

#1545 #1377 - Add public endpoints to OpenAPI swagger document
  documents/openapi/openapi.yaml
Labels: enhancement

#1547 Hotfix Logging Error in dao_update_notification_by_id
  app/dao/notifications_dao.py
Labels: hotfix

#1551 Hotfix to upgrade werkzeug
  requirements.txt
Labels: dependencies, Notify, hotfix, security

#1550 #1498 twilio callback overrides
  app/clients/sms/twilio.py
  app/version.py
  requirements_for_test.txt
  scripts/run_tests.sh
  tests/app/clients/test_twilio.py
Labels: enhancement
