Repository department-of-veterans-affairs/notification-api, pull requests merged in 2023-06, with the labels that each got.

#1311 #1253 Added routes and unit tests for CommunicationItem
  .talismanrc
  app/communication_item/communication_item_schemas.py
  app/communication_item/rest.py
  app/models.py
  migrations/versions/0359_communication_items_unique.py
  scripts/postman/notification-api.postman_collection.json
  tests/app/communication_item/test_rest.py
  tests/app/conftest.py
  tests/app/db.py
Labels: QA, enhancement

#1309 #1227 Explicit Logic for Communication Items
  app/celery/lookup_recipient_communication_permissions_task.py
  app/va/va_profile/va_profile_client.py
  tests/app/celery/test_lookup_recipient_communication_permissions_task.py
Labels: enhancement

#1317 #1268 Updated the OpenAPI specification and Postman collection for CommunicationItem
  documents/openapi/openapi.yaml
  scripts/postman/notification-api.postman_collection.json
Labels: enhancement

#1304 Action Required: Configure CodeQL
  .github/codeql.yml
  .github/emass.json
  .github/workflows/codeql-analysis.yml
  .github/workflows/codeql.yml
Labels: github_actions, security

#1328 #1214 Fix Pre-release Trigger for GitHub Actions
  .github/workflows/release_trigger.yml
Labels: devops

#1325 #1241 June Routine upgrades
  Makefile
  requirements-app.txt
  requirements.txt
Labels: dependencies, Notify

#1331 #1214 Fix Pre-release Trigger for GitHub Actions
  .github/workflows/release.yml
  .github/workflows/release_trigger.yml
Labels: devops

#1338 #1214 final fix
  .github/workflows/release_trigger.yml
Labels: devops

#1335 #1241 Routine upgrades (revision 1)
  .talismanrc
  Makefile
  lambda_functions/va_profile/requirements-lambda.txt
  requirements-app.txt
  requirements.txt
  requirements_for_test.txt
  tests/app/oauth/test_rest.py
Labels: dependencies, enhancement, security

#1332 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/spike-template.md
  .github/ISSUE_TEMPLATE/story-template.md
  .github/pull_request_template.md
Labels: enhancement

#1347 #870 Celery Upgrade
  Makefile
  app/config.py
  requirements-app.txt
  requirements.txt
  run_celery.py
Labels: dependencies, security
