Repository department-of-veterans-affairs/notification-api, pull requests merged in 2023-12, with the labels that each got.

#1558 Ignore pypdf
  Makefile
  requirements-app.txt
Labels: bug

#1566 Updated to use protected admin user name
  app/config.py
  cd/application-deployment/dev/vaec-api-task-definition.json
  cd/application-deployment/perf/vaec-api-task-definition.json
  cd/application-deployment/prod/vaec-api-task-definition.json
  cd/application-deployment/staging/vaec-api-task-definition.json
Labels: hotfix

#1570 #1552 Updating requirements.
  Makefile
  requirements-app.txt
  requirements.txt
Labels: dependencies

#1561 #1189 Validate twilio requests, associated tests and requirements.
  lambda_functions/delivery_status_processor_lambda/delivery_status_processor_lambda.py
  lambda_functions/delivery_status_processor_lambda/requirements-lambda.txt
  lambda_functions/vetext_incoming_forwarder_lambda/requirements-lambda.txt
  lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
  tests/lambda_functions/delivery_status_processor_lambda/test_delivery_status_processor_lambda.py
  tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
Labels: enhancement, lambda

#1572 #1189 adding info logging
  lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
Labels: enhancement

#1559 #1535 Two Way Message Enhancement: Support for All Clients
  .talismanrc
  app/inbound_number/inbound_number_schema.py
  app/inbound_number/rest.py
  app/models.py
  documents/openapi/openapi.yaml
  lambda_functions/two_way_sms/two_way_sms_v2.py
  migrations/versions/0367_add_auth_parameter.py
  scripts/postman/notification-api.postman_collection.json
  tests/app/db.py
  tests/lambda_functions/two_way_sms/test_two_way_sms_v2.py
Labels: enhancement

#1576 Hotfix Vetext Forwarder Params
  lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
Labels: hotfix

#1577 HOTFIX Update boto3 Client Invocation
  lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
Labels: hotfix
