Repository department-of-veterans-affairs/notification-api, pull requests merged in 2023-08, with the labels that each got.

#1401 #1376 Update our Twilio error codes to handle the new 30034
  .talismanrc
  app/celery/provider_tasks.py
  app/clients/sms/twilio.py
  tests/app/clients/test_twilio.py
Labels: enhancement

#1409 Exception Retry Hotfix
  app/celery/common.py
  app/celery/provider_tasks.py
Labels: hotfix

#1414 Upgrade Postgres containers from v11 to v15
  .github/workflows/tests.yaml
  README.md
  ci/docker-compose-local-migrate.yml
  ci/docker-compose-local.yml
  ci/docker-compose-test.yml
  ci/docker-compose.yml
  tests/app/dao/test_services_dao.py
Labels: docker, Notify, enhancement

#1416 Docker ECR Login action
  .github/workflows/build.yml
  .github/workflows/db-downgrade.yml
  .github/workflows/deployment.yml
  .github/workflows/twistlock.yml
  .github/workflows/update-datadog-image.yaml
Labels: github_actions, devops

#1420 #1419 Hotfix AttributeError and RuntimeError catch
  app/celery/common.py
  app/celery/provider_tasks.py
Labels: hotfix

#1422 #1419 Halt Celery processing to send a notification if VA Profile times outand trigger a retry
  .talismanrc
  app/celery/contact_information_tasks.py
  app/celery/provider_tasks.py
  app/va/va_profile/va_profile_client.py
  tests/app/celery/test_contact_information_tasks.py
Labels: bug

#1426 Hotfix AutoRetry For Rate Limiting SMS Deliveries
  app/celery/provider_tasks.py
  app/notifications/validators.py
  tests/app/celery/test_provider_tasks.py
  tests/app/notifications/test_validators.py
Labels: hotfix

#1427 626 Twistlock Re-added
  .github/workflows/build.yml
Labels: devops

#1429 1149 - Clean up letter-branding related code and db
  app/__init__.py
  app/celery/letters_pdf_tasks.py
  app/commands.py
  app/dao/letter_branding_dao.py
  app/dao/services_dao.py
  app/letter_branding/__init__.py
  app/letter_branding/letter_branding_rest.py
  app/letter_branding/letter_branding_schema.py
  app/models.py
  app/schemas.py
  app/service/rest.py
  app/template/rest.py
  documents/openapi/openapi-with-push.yaml
  documents/openapi/openapi.yaml
  migrations/versions/0361_remove_letter_branding.py
  tests/app/celery/test_letters_pdf_tasks.py
  tests/app/dao/test_letter_branding_dao.py
  tests/app/dao/test_organisation_dao.py
  tests/app/dao/test_services_dao.py
  tests/app/db.py
  tests/app/letter_branding/__init__.py
  tests/app/letter_branding/test_letter_branding_rest.py
  tests/app/organisation/test_rest.py
  tests/app/service/test_rest.py
Labels: enhancement

#1430 #1360 Implement POST /v3/notifications, including tests and API specifications
  .github/workflows/tests.yaml
  .talismanrc
  Makefile
  app/__init__.py
  app/authentication/auth.py
  app/feature_flags.py
  app/models.py
  app/v3/__init__.py
  app/v3/notifications/__init__.py
  app/v3/notifications/notification_schemas.py
  app/v3/notifications/rest.py
  cd/application-deployment/dev/vaec-api-task-definition.json
  cd/application-deployment/perf/vaec-api-task-definition.json
  cd/application-deployment/prod/vaec-api-task-definition.json
  cd/application-deployment/staging/vaec-api-task-definition.json
  ci/.docker-env.example
  ci/docker-compose-test.yml
  documents/openapi/openapi.yaml
  scripts/postman/notification-api.postman_collection.json
  tests/app/v3/__init__.py
  tests/app/v3/notifications/__init__.py
  tests/app/v3/notifications/test_notification_schemas.py
  tests/app/v3/notifications/test_rest.py
  tests/env_vars
Labels: enhancement
