Repository department-of-veterans-affairs/notification-api, pull requests merged in 2023-07, with the labels that each got.

#1373 #561 Profiler ddtrace errors
  application.py
  cd/application-deployment/dev/vaec-celery-beat-task-definition.json
  cd/application-deployment/dev/vaec-celery-task-definition.json
  cd/application-deployment/perf/vaec-celery-beat-task-definition.json
  cd/application-deployment/perf/vaec-celery-task-definition.json
  cd/application-deployment/prod/vaec-celery-beat-task-definition.json
  cd/application-deployment/prod/vaec-celery-task-definition.json
  cd/application-deployment/staging/vaec-celery-beat-task-definition.json
  cd/application-deployment/staging/vaec-celery-task-definition.json
  ci/Dockerfile
  ci/Dockerfile.local
Labels: devops

#1367 #1226 Celery Retry Exponential Backoff
  app/celery/common.py
  app/celery/contact_information_tasks.py
  app/celery/exceptions.py
  app/celery/lookup_recipient_communication_permissions_task.py
  app/celery/lookup_va_profile_id_task.py
  app/celery/process_delivery_status_result_tasks.py
  app/celery/process_pinpoint_receipt_tasks.py
  app/celery/provider_tasks.py
  app/celery/service_callback_tasks.py
  tests/app/celery/test_contact_information_tasks.py
  tests/app/celery/test_lookup_va_profile_id_task.py
  tests/app/celery/test_process_delivery_status_result_tasks.py
  tests/app/celery/test_provider_tasks.py
  tests/app/celery/test_service_callback_tasks.py
  tests/app/notifications/test_rest.py
Labels: enhancement

#1394 Autoretry Logging Update
  app/celery/common.py
  app/celery/contact_information_tasks.py
  app/celery/lookup_recipient_communication_permissions_task.py
  app/celery/lookup_va_profile_id_task.py
  app/celery/provider_tasks.py
Labels: enhancement

#1399 Remove Twistlock
  .github/workflows/build.yml
  Makefile
Labels: github_actions, devops
