Repository department-of-veterans-affairs/notification-api, pull requests merged in 2023-10, with the labels that each got.

#1478 #1442 add regression to tag trigger
  .github/workflows/tag_trigger.yml
  README.md
Labels: devops

#1481 #1480 Reduced Unnecessary Database Queries
  app/service/service_data.py
  tests/app/template/test_rest.py
Labels: bug

#1486 #1327 Run QA suite on staging pre-release trigger
  .github/workflows/dev_deploy.yml
  .github/workflows/prerelease_trigger.yml
  .github/workflows/regression-public.yml
  .github/workflows/tag_trigger.yml
Labels: devops

#1487 #1472 Update Dependencies
  load_testing/requirements_cli.txt
  requirements-app.txt
  requirements.txt
Labels: dependencies

#1490 Hotfix - remove run-qa-suite from deploy, tag and pre-release
  .github/workflows/dev_deploy.yml
  .github/workflows/prerelease_trigger.yml
  .github/workflows/tag_trigger.yml
Labels: hotfix

#1491 #1472 Update Dependencies - Github Actions
  .github/workflows/build.yml
  .github/workflows/db-downgrade.yml
  .github/workflows/deploy_lambda_dev.yml
  .github/workflows/deployment.yml
  .github/workflows/dev_deploy.yml
  .github/workflows/lambda-functions.yml
  .github/workflows/load-test-email-delivery-time.yaml
  .github/workflows/load-test-sms-response-time.yaml
  .github/workflows/regression-public.yml
  .github/workflows/tests.yaml
  .github/workflows/twistlock.yml
  .github/workflows/update-cached-image.yaml
  .github/workflows/update-datadog-image.yaml
  .github/workflows/user_flows.yml
Labels: dependencies

#1492 Task CPU and Memory Update
  .github/workflows/dev_deploy.yml
  cd/application-deployment/dev/vaec-api-task-definition.json
  cd/application-deployment/dev/vaec-celery-beat-task-definition.json
  cd/application-deployment/dev/vaec-celery-task-definition.json
  cd/application-deployment/dev/vaec-db-downgrade-task-definition.json
  cd/application-deployment/dev/vaec-db-migrations-task-definition.json
  cd/application-deployment/staging/vaec-api-task-definition.json
  cd/application-deployment/staging/vaec-celery-beat-task-definition.json
  cd/application-deployment/staging/vaec-celery-task-definition.json
  cd/application-deployment/staging/vaec-db-downgrade-task-definition.json
  cd/application-deployment/staging/vaec-db-migrations-task-definition.json
Labels: devops

#1483 #1361 v3 basic send logic (part 1)
  .talismanrc
  app/celery/v3/__init__.py
  app/celery/v3/notification_tasks.py
  app/config.py
  app/models.py
  app/v3/__init__.py
  app/v3/notifications/rest.py
  tests/app/celery/v3/test_notification_tasks.py
  tests/app/conftest.py
  tests/app/v3/notifications/test_rest.py
Labels: enhancement

#1494 #1361 v3 basic send logic (part 2)
  app/celery/v3/notification_tasks.py
Labels: enhancement

#1496 Two Way SMS Logging Hotfix
  lambda_functions/two_way_sms/two_way_sms_v2.py
Labels: hotfix

#1500 #1169 - Add template_p2p_checklist table
  app/models.py
  migrations/versions/0364_add_templatep2pchecklist.py
Labels: enhancement

#1519 Hotfix to Return 201 on PUSH Timeout
  app/va/vetext/client.py
  tests/app/v2/notifications/test_push_notifications.py
Labels: hotfix

#1516 #1488 BUG: Twilio delivered messages getting stuck in sent
  app/celery/process_delivery_status_result_tasks.py
  app/celery/process_pinpoint_receipt_tasks.py
  app/dao/notifications_dao.py
  tests/app/dao/notification_dao/test_notification_dao.py
  tests/app/service/test_rest.py
Labels: bug
