Repository department-of-veterans-affairs/notification-api, pull requests merged in 2024-05, with the labels that each got.

#1767 Hotfix - Added Event To Logging
  lambda_functions/delivery_status_processor_lambda/delivery_status_processor_lambda.py
Labels: hotfix

#1772 getting labels from new payload - pr push
  testfile2
Labels: bug

#1773 getting labels from new payload - pr push
  testfile2
Labels: bug

#1775 getting labels from new payload - organized code for readability and …
  testfile2
Labels: bug

#1774 #1765 Remove the outdated CodeQL scan workflow
  .github/workflows/codeql-analysis.yml
Labels: internal

#1777 Revert "1727 test"
  testfile2
Labels: bug

#1778 getting release branch SHA - return data.sha
  testfile2
Labels: bug

#1783 Fix VEText Push URL in Staging
  app/config.py
Labels: hotfix

#1785 testing pipeline with permissions update
  testfile
Labels: bug

#1786 testing pipeline with permissions update
  testfile
Labels: bug

#1790 preparing test with QA - passing github token from cd pipeline
  testfile
Labels: bug

#1784 #1750 Update task definitions for Comp & Pen
  cd/application-deployment/dev/vaec-api-task-definition.json
  cd/application-deployment/dev/vaec-celery-beat-task-definition.json
  cd/application-deployment/dev/vaec-celery-task-definition.json
  cd/application-deployment/perf/vaec-api-task-definition.json
  cd/application-deployment/perf/vaec-celery-beat-task-definition.json
  cd/application-deployment/perf/vaec-celery-task-definition.json
  cd/application-deployment/prod/vaec-api-task-definition.json
  cd/application-deployment/prod/vaec-celery-beat-task-definition.json
  cd/application-deployment/prod/vaec-celery-task-definition.json
  cd/application-deployment/staging/vaec-api-task-definition.json
  cd/application-deployment/staging/vaec-celery-beat-task-definition.json
  cd/application-deployment/staging/vaec-celery-task-definition.json
Labels: enhancement

#1793 #1750 revision to correct syntax error
  cd/application-deployment/dev/vaec-api-task-definition.json
  cd/application-deployment/dev/vaec-celery-beat-task-definition.json
  cd/application-deployment/dev/vaec-celery-task-definition.json
  cd/application-deployment/perf/vaec-api-task-definition.json
  cd/application-deployment/perf/vaec-celery-beat-task-definition.json
  cd/application-deployment/perf/vaec-celery-task-definition.json
  cd/application-deployment/prod/vaec-api-task-definition.json
  cd/application-deployment/prod/vaec-celery-beat-task-definition.json
  cd/application-deployment/prod/vaec-celery-task-definition.json
  cd/application-deployment/staging/vaec-api-task-definition.json
  cd/application-deployment/staging/vaec-celery-beat-task-definition.json
  cd/application-deployment/staging/vaec-celery-task-definition.json
Labels: bug

#1795 #1747 Moved the location of the Comp & Pen feature flag check
  app/celery/scheduled_tasks.py
  cd/application-deployment/perf/vaec-api-task-definition.json
  cd/application-deployment/perf/vaec-celery-beat-task-definition.json
  cd/application-deployment/perf/vaec-celery-task-definition.json
Labels: enhancement, internal

#1781 #1752 Send SMS to Amazon Deliverable Number in Perf
  .talismanrc
  app/celery/scheduled_tasks.py
  app/config.py
  app/notifications/send_notifications.py
  cd/application-deployment/perf/vaec-api-task-definition.json
  cd/application-deployment/perf/vaec-celery-beat-task-definition.json
  cd/application-deployment/perf/vaec-celery-task-definition.json
  tests/app/celery/test_scheduled_tasks.py
  tests/app/notifications/test_send_notifications.py
Labels: internal

#1733 #1727 CD Pipeline Tag Versioning
  .github/scripts/actionUtils.js
  .github/scripts/createAndPostTag.js
  .github/scripts/prData.js
  .github/scripts/prLabelSemver.js
  .github/scripts/preTagSummary.js
  .github/workflows/cd-pipeline.yml
  .github/workflows/create-and-post-tag.yml
  .github/workflows/pr-label-semver.yml
  .github/workflows/pre-tag-summary.yml
Labels: devops

#1803 #1749 Comp & Pen SMS sender ID
  .talismanrc
  app/celery/scheduled_tasks.py
  app/config.py
  cd/application-deployment/dev/vaec-api-task-definition.json
  cd/application-deployment/dev/vaec-celery-beat-task-definition.json
  cd/application-deployment/dev/vaec-celery-task-definition.json
  cd/application-deployment/perf/vaec-api-task-definition.json
  cd/application-deployment/perf/vaec-celery-beat-task-definition.json
  cd/application-deployment/perf/vaec-celery-task-definition.json
  cd/application-deployment/prod/vaec-api-task-definition.json
  cd/application-deployment/prod/vaec-celery-beat-task-definition.json
  cd/application-deployment/prod/vaec-celery-task-definition.json
  cd/application-deployment/staging/vaec-api-task-definition.json
  cd/application-deployment/staging/vaec-celery-beat-task-definition.json
  cd/application-deployment/staging/vaec-celery-task-definition.json
  tests/app/celery/test_scheduled_tasks.py
Labels: enhancement

#1805 #1727 CD Pipeline Tag Versioning
  .github/scripts/actionUtils.js
  .github/scripts/createAndPostTag.js
  .github/scripts/prData.js
  .github/scripts/prLabelSemver.js
  .github/scripts/preTagSummary.js
  .github/workflows/cd-pipeline.yml
  .github/workflows/create-and-post-tag.yml
  .github/workflows/pr-label-semver.yml
  .github/workflows/pre-tag-summary.yml
Labels: devops

#1806 Update the DigiCert Global G2 CA certificate.
  .talismanrc
  certs/DigiCert-Global-G2-TLS-RSA-SHA256-2020-CA1.cer
Labels: Notify, internal

#1811 #1725 - Squash and Merge Release
  .github/workflows/cd-pipeline.yml
Labels: bug

#1809 #1725 Version Release Notes Generation
  .github/scripts/actionUtils.js
  .github/scripts/createAndPostTag.js
  .github/scripts/createReleaseNotes.js
  .github/scripts/prData.js
  .github/scripts/prLabelSemver.js
  .github/scripts/preTagSummary.js
  .github/workflows/cd-pipeline.yml
  .github/workflows/create-and-post-tag.yml
  .github/workflows/create-release-notes.yml
Labels: actions

#1815 #1721 - Precursor Updates
  .github/release.yaml
  .github/scripts/trigger-regression.js
  .github/workflows/deploy-release.yml
  .github/workflows/prerelease_trigger.yml
  .github/workflows/release_trigger.yml
Labels: internal

#1817 #1816 - Added Additional Auth and Encryption
  lambda_functions/vetext_incoming_forwarder_lambda/twilio_signature_utils.py
  lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
  tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
Labels: bug

#1825 #1819 Add fields to VAProfile cache table
  app/models.py
  migrations/versions/0369_vaprofile_cache_fields.py
Labels: internal

#1813 #1721 Publish Release Notes
  .github/scripts/actionUtils.js
  .github/scripts/createAndPostTag.js
  .github/scripts/createReleaseNotes.js
  .github/scripts/prData.js
  .github/scripts/prLabelSemver.js
  .github/scripts/preTagSummary.js
  .github/scripts/publishReleaseNotes.js
  .github/scripts/trigger-regression.js
  .github/workflows/cd-pipeline.yml
  .github/workflows/create-and-post-tag.yml
  .github/workflows/create-release-notes.yml
  .github/workflows/deploy-release.yml
  .github/workflows/publish-release-notes.yml
Labels: internal

#1824 #1823 BUG: Comp & Pen - Not Processing Table Items
  app/celery/scheduled_tasks.py
  tests/app/celery/test_scheduled_tasks.py
Labels: bug
