Repository department-of-veterans-affairs/notification-api, pull requests merged in 2024-09, with the labels that each got.

#1980 #1662 - Upgrade ddtrace to latest version
  poetry.lock
  pyproject.toml
Labels: internal

#1984 Hotfix - Update PR template to remove 'Type of Change' section
  .github/pull_request_template.md
Labels: internal

#1986 Update Story Templates - Add Checkbox for Review Slide Content
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/notify-dependency-update-template.md
  .github/ISSUE_TEMPLATE/spike-template.md
  .github/ISSUE_TEMPLATE/story-template.md
Labels: internal

#1987 UTILS-163 dependency upgrades
  .talismanrc
  poetry.lock
Labels: internal

#1989 HOTFIX - Updated Log Level and Message For Delivery Status "should_exit"
  app/celery/process_delivery_status_result_tasks.py
Labels: internal

#1988 #1224 Marshmallow Upgrade
  .talismanrc
  app/accept_invite/rest.py
  app/communication_item/rest.py
  app/events/rest.py
  app/invite/rest.py
  app/job/rest.py
  app/notifications/rest.py
  app/oauth/rest.py
  app/provider_details/rest.py
  app/schemas.py
  app/service/callback_rest.py
  app/service/rest.py
  app/template/rest.py
  app/template_statistics/rest.py
  poetry.lock
  pyproject.toml
  tests/app/dao/test_service_callback_api_dao.py
  tests/app/dao/test_templates_dao.py
  tests/app/notifications/rest/test_send_notification.py
  tests/app/service/test_callback_rest.py
  tests/app/service/test_rest.py
  tests/app/template/test_rest.py
  tests/app/test_schemas.py
Labels: internal

#1990 #1977 Bug: Update to Delivered After Other Status is Assigned
  app/celery/process_delivery_status_result_tasks.py
  app/celery/process_pinpoint_receipt_tasks.py
  app/dao/notifications_dao.py
  tests/app/celery/test_process_pinpoint_receipt_tasks.py
  tests/app/celery/test_tasks.py
  tests/app/dao/notification_dao/test_notification_dao.py
Labels: bug

#1996 HOTFIX - Refactored Celery to Reduce Time Polling SQS
  .talismanrc
  README.md
  app/celery/provider_tasks.py
  app/celery/reporting_tasks.py
  app/celery/research_mode_tasks.py
  app/celery/scheduled_tasks.py
  app/celery/tasks.py
  app/config.py
  app/job/rest.py
  app/letters/rest.py
  app/notifications/process_notifications.py
  app/notifications/rest.py
  app/service/send_notification.py
  app/v2/notifications/post_notifications.py
  lambda_functions/pinpoint_callback/pinpoint_callback_lambda.py
  lambda_functions/ses_callback/ses_callback_lambda.py
  scripts/run_celery.sh
  scripts/trigger_task.py
  tests/app/celery/test_provider_tasks.py
  tests/app/celery/test_research_mode_tasks.py
  tests/app/celery/test_scheduled_tasks.py
  tests/app/celery/test_tasks.py
  tests/app/letters/test_returned_letters.py
  tests/app/notifications/rest/test_send_notification.py
  tests/app/notifications/test_process_notifications.py
  tests/app/service/test_send_one_off_notification.py
  tests/app/test_config.py
  tests/app/v2/notifications/test_post_notifications.py
Labels: hotfix

#1999 #1970 - Simplify labeling scheme to major, minor, patch
  .github/release.yaml
  .github/scripts/prData.js
  .github/scripts/prLabelSemver.js
Labels: patch

#2005 #1970 - Update PR template to point to current labeling scheme
  .github/pull_request_template.md
Labels: patch

#2006 #1970 - Set category for release notes to empty string
  .github/release.yaml
Labels: patch

#2007 HOTFIX - Updated Permission Logic
  .talismanrc
  app/celery/contact_information_tasks.py
  app/celery/lookup_recipient_communication_permissions_task.py
  app/va/va_profile/va_profile_client.py
  tests/app/celery/test_contact_information_tasks.py
  tests/app/conftest.py
  tests/app/va/va_profile/test_va_profile_client.py
  tests/app/va/va_profile/test_va_profile_client_for_profile_v3.py
Labels: patch

#2008 #1948 GA4 Validation errors
  .talismanrc
  app/celery/process_ga4_measurement_tasks.py
  app/config.py
  app/googleanalytics/ga4.py
  app/googleanalytics/ga4_schemas.py
  app/googleanalytics/pixels.py
  tests/app/celery/test_process_ga4_measurement_task.py
  tests/app/googleanalytics/test_ga4_rest.py
  tests/app/googleanalytics/test_ga4_schemas.py
  tests/app/googleanalytics/test_pixels.py
  tests/app/test_route_authentication.py
Labels: patch

#2017 BUGFIX - Added to reply_to_text For Comp And Pen
  app/clients/sms/aws_pinpoint.py
  app/clients/sms/twilio.py
  app/dao/service_sms_sender_dao.py
  app/dao/templates_dao.py
  app/integrations/comp_and_pen/scheduled_message_helpers.py
  app/models.py
  app/notifications/send_notifications.py
  tests/app/celery/test_tasks.py
  tests/app/integrations/comp_and_pen/test_scheduled_message_helpers.py
  tests/app/notifications/test_send_notifications.py
Labels: patch

#2018 #1780 - Prod: Configure the send email notification delivery status to VA Profile
  cd/application-deployment/prod/vaec-celery-task-definition.json
Labels: patch

#2010 #2009 - IIR - Update VAPRO Contact Lookup to Filter by Valid Phone Numbers
  .talismanrc
  app/va/va_profile/va_profile_client.py
  app/va/va_profile/va_profile_types.py
  cd/application-deployment/dev/vaec-celery-task-definition.json
  cd/application-deployment/perf/vaec-celery-task-definition.json
  cd/application-deployment/prod/vaec-celery-task-definition.json
  cd/application-deployment/staging/vaec-celery-task-definition.json
  tests/app/va/va_profile/mock_response.json
  tests/app/va/va_profile/test_va_profile_client.py
  tests/app/va/va_profile/test_va_profile_client_for_profile_v3.py
Labels: internal

#2020 #1466 - Pinpoint Lambda Speedup
  .talismanrc
  ci/docker-compose-test.yml
  lambda_functions/pinpoint_callback/pinpoint_callback_lambda.py
  tests/lambda_functions/pinpoint_callback/test_pinpoint_callback_lambda.py
Labels: patch
