Repository department-of-veterans-affairs/notification-api, pull requests merged in 2024-07, with the labels that each got.

#1850 TEAM-1326 Add Link to PR Template for Naming Documentation
  .github/pull_request_template.md
Labels: internal

#1851 #1794 Remove flask-cors Dependency
  .talismanrc
  Makefile
  app/__init__.py
  app/oauth/rest.py
  ci/Dockerfile
  poetry.lock
  pyproject.toml
  tests/app/oauth/test_rest.py
Labels: internal

#1861 Hotfix - Update Dependency Issue Template
  .github/ISSUE_TEMPLATE/notify-dependency-update-template.md
Labels: internal

#1859 #1853 - Create the route GET /ga4/open-email-tracking.
  app/__init__.py
  app/googleanalytics/ga4.py
  app/googleanalytics/ga4_schemas.py
  tests/app/googleanalytics/conftest.py
  tests/app/googleanalytics/test_ga4_rest.py
  tests/app/googleanalytics/test_ga4_schemas.py
  tests/app/test_route_authentication.py
Labels: enhancement

#1863 #1853 - Log validation errors
  app/googleanalytics/ga4.py
Labels: enhancement

#1864 #1839 Remove the set-python action from the lambda-functions.yml workflow
  .github/workflows/lambda-functions.yml
Labels: internal

#1866 HOTFIX - Update Comp & Pen Personalization
  app/integrations/comp_and_pen/scheduled_message_helpers.py
  tests/app/integrations/comp_and_pen/test_scheduled_message_helpers.py
Labels: hotfix

#1867 #1624 Update moto for Test Container
  .talismanrc
  poetry.lock
  pyproject.toml
  tests/app/conftest.py
  tests/app/letters/test_letter_utils.py
  tests/lambda_functions/two_way_sms/test_two_way_sms_v2.py
Labels: internal

#1868 HOTFIX - Cleaned VEText Forwarder Logging
  lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
  tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
Labels: hotfix

#1860 #1847 - Build dynamic GA4 URL
  app/celery/v3/notification_tasks.py
  app/config.py
  app/delivery/send_to_providers.py
  app/googleanalytics/ga4.py
  app/googleanalytics/pixels.py
  ci/Dockerfile
  images/ga4_pixel_tracking.png
  poetry.lock
  tests/app/delivery/test_send_to_providers.py
  tests/app/googleanalytics/test_ga4_rest.py
  tests/app/googleanalytics/test_pixels.py
Labels: internal

#1871 Updated PR and Story Templates
  .github/ISSUE_TEMPLATE/lambda-dependency-update-template.md
  .github/ISSUE_TEMPLATE/story-template.md
  .github/pull_request_template.md
Labels: internal

#1869 #1854 GA4 Migration: Celery task to post GA4 event
  .talismanrc
  app/celery/process_ga4_measurement_tasks.py
  app/config.py
  app/googleanalytics/ga4.py
  cd/application-deployment/dev/vaec-celery-task-definition.json
  cd/application-deployment/perf/vaec-celery-task-definition.json
  cd/application-deployment/prod/vaec-celery-task-definition.json
  cd/application-deployment/staging/vaec-celery-task-definition.json
  ci/.local.env
  tests/app/celery/conftest.py
  tests/app/celery/test_process_ga4_measurement_task.py
  tests/app/googleanalytics/test_ga4_rest.py
Labels: internal

#1878 IIR-890|894|899 - Add Feature Flags for Profile V3 Upgrade
  app/feature_flags.py
Labels: internal

#1879 #1865 Correct KeyError for Pinpoint OPTED_OUT response
  app/celery/process_pinpoint_receipt_tasks.py
  tests/app/celery/test_process_pinpoint_receipt_tasks.py
Labels: bug

#1881 #1713 Internal Blueprint and Generic Endpoints
  .talismanrc
  README.md
  app/__init__.py
  app/internal/rest.py
  tests/app/internal/__init__.py
  tests/app/internal/test_rest.py
  tests/app/test_route_authentication.py
Labels: internal

#1884 Updated readme
  README.md
Labels: internal

#1883 UTILS-159 - Update pixel image to have alt text
  poetry.lock
Labels: internal

#1885 #1857 Dependency Update
  .github/workflows/build.yml
  .talismanrc
  README.md
  load_testing/requirements.txt
  load_testing/requirements_cli.txt
  poetry.lock
  pyproject.toml
Labels: internal

#1887 #1858 - Add currency formatting for payment amount
  app/integrations/comp_and_pen/scheduled_message_helpers.py
  tests/app/integrations/comp_and_pen/test_scheduled_message_helpers.py
Labels: internal

#1893 UTILS-154 Use the latest notification-utils commit
  .talismanrc
  poetry.lock
Labels: enhancement

#1894 HOTFIX - Changed error to warning for retryable failures
  .pre-commit-config.yaml
  lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
Labels: hotfix
