Repository department-of-veterans-affairs/notification-api, pull requests merged in 2024-03, with the labels that each got.

#1680 Add Dev Test Workflow Dispatch/Call Github Action
  .github/workflows/dev-tests.yml
  .talismanrc
Labels: devops

#1671 #1661 - Delete skipped and xfailed tests for route removal
  tests/app/accept_invite/test_accept_invite_rest.py
  tests/app/api_key/test_rest.py
  tests/app/celery/test_ftp_update_tasks.py
  tests/app/celery/test_letters_pdf_tasks.py
  tests/app/celery/test_process_delivery_status_result_tasks.py
  tests/app/celery/test_process_ses_receipts_tasks.py
  tests/app/celery/test_provider_tasks.py
  tests/app/celery/test_reporting_tasks.py
  tests/app/celery/test_scheduled_tasks.py
  tests/app/celery/test_tasks.py
  tests/app/dao/notification_dao/test_notification_dao.py
  tests/app/dao/test_ft_billing_dao.py
  tests/app/dao/test_jobs_dao.py
  tests/app/dao/test_organisation_dao.py
  tests/app/dao/test_provider_details_dao.py
  tests/app/dao/test_service_letter_contact_dao.py
  tests/app/dao/test_service_sms_sender_dao.py
  tests/app/dao/test_services_dao.py
  tests/app/dao/test_users_dao.py
  tests/app/email_branding/test_rest.py
  tests/app/invite/__init__.py
  tests/app/invite/test_invite_rest.py
  tests/app/job/__init__.py
  tests/app/job/test_rest.py
  tests/app/letters/test_letter_utils.py
  tests/app/notifications/rest/test_callbacks.py
  tests/app/notifications/rest/test_send_notification.py
  tests/app/notifications/test_aws_sns_status_callback.py
  tests/app/notifications/test_process_letter_notifications.py
  tests/app/notifications/test_process_notifications.py
  tests/app/notifications/test_receive_notification.py
  tests/app/notifications/test_rest.py
  tests/app/oauth/test_rest.py
  tests/app/organisation/test_invite_rest.py
  tests/app/organisation/test_rest.py
  tests/app/service/test_archived_service.py
  tests/app/service/test_rest.py
  tests/app/service/test_send_one_off_notification.py
  tests/app/service/test_service_data_retention_rest.py
  tests/app/service/test_service_whitelist.py
  tests/app/service/test_statistics_rest.py
  tests/app/service/test_suspend_resume_service.py
  tests/app/status/test_status.py
  tests/app/template/test_rest.py
  tests/app/template/test_rest_history.py
  tests/app/template_folder/test_template_folder_rest.py
  tests/app/test_model.py
  tests/app/test_schemas.py
  tests/app/user/test_rest.py
  tests/app/user/test_rest_verify.py
  tests/app/v2/notifications/test_get_notifications.py
  tests/app/v2/notifications/test_post_letter_notifications.py
  tests/app/v2/notifications/test_post_notifications.py
Labels: Tech Debt

#1674 #1635 Remove Unused Pytest Fixtures
  tests/README.md
  tests/app/celery/test_process_delivery_status_result_tasks.py
  tests/app/celery/test_service_callback_tasks.py
  tests/app/celery/test_tasks.py
  tests/app/conftest.py
  tests/app/dao/test_organisation_dao.py
  tests/app/delivery/test_send_to_providers.py
  tests/app/integration/test_callback.py
  tests/app/notifications/rest/test_send_notification.py
  tests/app/notifications/test_aws_sns_status_callback.py
  tests/app/notifications/test_process_notifications.py
  tests/app/service/test_send_one_off_notification.py
  tests/app/service/test_sms_sender_rest.py
  tests/app/template/test_rest.py
  tests/app/v2/notifications/test_post_notifications.py
Labels: bug, Tech Debt

#1681 #1668 - Workflow Requiring QA approval to Deploy to Perf and Merge to Release Branch
  .github/workflows/deploy-to-perf.yml
  .github/workflows/dev_deploy.yml
Labels: devops

#1696 #1692 Updated for READMEs for Poetry
  .github/ISSUE_TEMPLATE/notify-dependency-update-template.md
  README.md
  ci/.docker-env.example
  ci/README.md
  tests/README.md
Labels: internal

#1705 #1697 Delete Cache Action
  .github/workflows/update-cached-image.yaml
Labels: bug

#1706 HOTFIX - Updated to Lambda Deploy To Allow Environment
  .github/workflows/deploy_lambda_dev.yml
  .github/workflows/dev_deploy.yml
Labels: hotfix, devops

#1698 #1688 vetext2 inbound forwarding
  lambda_functions/vetext_incoming_forwarder_lambda/twilio_signature_utils.py
  lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
  tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
Labels: enhancement

#1708 #1703 Fix Twilio Error Results in Retries on TwilioRestException
  app/clients/sms/aws_pinpoint.py
  app/clients/sms/twilio.py
  tests/app/clients/test_aws_pinpoint.py
  tests/app/clients/test_twilio.py
Labels: bug

#1704 #1689 Update Comp & Pen notification filters
  .talismanrc
  app/celery/scheduled_tasks.py
  app/config.py
  cd/application-deployment/dev/vaec-api-task-definition.json
  cd/application-deployment/dev/vaec-celery-beat-task-definition.json
  cd/application-deployment/dev/vaec-celery-task-definition.json
  cd/application-deployment/perf/vaec-api-task-definition.json
  cd/application-deployment/perf/vaec-celery-beat-task-definition.json
  cd/application-deployment/perf/vaec-celery-task-definition.json
  cd/application-deployment/prod/vaec-api-task-definition.json
  cd/application-deployment/prod/vaec-celery-beat-task-definition.json
  cd/application-deployment/prod/vaec-celery-task-definition.json
  cd/application-deployment/staging/vaec-api-task-definition.json
  cd/application-deployment/staging/vaec-celery-beat-task-definition.json
  cd/application-deployment/staging/vaec-celery-task-definition.json
  tests/README.md
  tests/app/celery/test_scheduled_tasks.py
Labels: enhancement
