Repository department-of-veterans-affairs/notification-api, pull requests merged in 2024-04, with the labels that each got.

#1715 #1479 Remove unused celery letters-pdf task
  app/celery/letters_pdf_tasks.py
  app/celery/tasks.py
  app/commands.py
  app/config.py
  app/dao/notifications_dao.py
  app/letters/utils.py
  app/notifications/process_letter_notifications.py
  app/notifications/process_notifications.py
  app/v2/notifications/post_notifications.py
  tests/app/celery/test_letters_pdf_tasks.py
  tests/app/dao/notification_dao/test_notification_dao.py
  tests/app/letters/test_letter_utils.py
  tests/app/notifications/test_process_notifications.py
  tests/app/test_config.py
Labels: Tech Debt

#1716 HOTFIX - Added environment to Action
  .github/workflows/run-regression.yml
Labels: internal

#1714 #1709 - Pipeline to Staging
  .github/workflows/cd-pipeline.yml
Labels: devops

#1720 HOTFIX - Updated Dependencies
  poetry.lock
  pyproject.toml
Labels: dependencies, hotfix, internal

#1718 #1707 Update Comp & Pen send notification scheduled task to use batch write
  app/celery/scheduled_tasks.py
  app/config.py
  tests/app/celery/test_scheduled_tasks.py
Labels: enhancement

#1734 testchange to merge a pr into other 1727 branch
  testchange
Labels: devops

#1737 #1215 Add unit tests, and improve API documentation, for creating and updating ServiceSmsSender instances
  app/service/service_senders_schema.py
  documents/openapi/openapi.yaml
  documents/postman/internal_api_developers/notification-api.postman_collection.json
  tests/app/service/test_sms_sender_rest.py
Labels: enhancement

#1742 Revert "test 2 - getting github.even object "
  testfile
Labels: bug

#1743 1727-label-test-pr
  .github/workflows/build.yml
  testchange
Labels: github_actions

#1741 #1685 New columns for ServiceSmsSender
  .gitignore
  app/models.py
  documents/openapi/openapi.yaml
  migrations/versions/0331_merge_service_apis.py
  migrations/versions/0368_servicesmssender_columns.py
Labels: enhancement

#1744 Revert "1727-label-test-pr"
  testchange
Labels: breaking-change

#1753 1434 Update Pinpoint SMS OPTOUT mapping
  app/celery/process_pinpoint_receipt_tasks.py
  tests/app/celery/test_process_pinpoint_receipt_tasks.py
Labels: bug

#1755 #1751 Dependency Update
  load_testing/requirements.txt
  poetry.lock
Labels: dependencies

#1763 Revert "Preparing PR - final test for PR closed trigger"
  testfile
Labels: bug

#1766 #183 - Add prod smoke test to prod deployments
  .github/workflows/dev_deploy.yml
  .github/workflows/release_trigger.yml
  .github/workflows/run-regression.yml
Labels: enhancement
