Repository department-of-veterans-affairs/notification-api, pull requests merged in 2024-02, with the labels that each got.

#1626 #1618 Remove Hard-coded Cipher List for MPI Connection
  app/va/mpi/mpi.py
Labels: security

#1639 #1630 [Bugfix] Bounce Handling
  app/celery/process_ses_receipts_tasks.py
  tests/app/celery/test_process_ses_receipts_tasks.py
Labels: bug

#1640 [Hotfix] ruff Format Fix
  .pre-commit-config.yaml
  .talismanrc
  app/celery/tasks.py
  app/dao/jobs_dao.py
  requirements_for_test.txt
  scripts/run_tests.sh
  tests/app/billing/test_billing.py
  tests/app/celery/test_nightly_tasks.py
  tests/app/celery/test_process_pinpoint_receipt_tasks.py
  tests/app/celery/test_reporting_tasks.py
  tests/app/celery/test_scheduled_tasks.py
  tests/app/celery/test_service_callback_tasks.py
  tests/app/celery/test_tasks.py
  tests/app/celery/v3/test_notification_tasks.py
  tests/app/communication_item/test_rest.py
  tests/app/conftest.py
  tests/app/dao/test_api_key_dao.py
  tests/app/dao/test_fact_notification_status_dao.py
  tests/app/dao/test_ft_billing_dao.py
  tests/app/dao/test_inbound_sms_dao.py
  tests/app/dao/test_provider_details_dao.py
  tests/app/dao/test_service_callback_api_dao.py
  tests/app/dao/test_services_dao.py
  tests/app/db.py
  tests/app/service/test_callback_rest.py
  tests/app/service/test_rest.py
  tests/app/template_folder/test_template_folder_rest.py
  tests/lambda_functions/va_profile/test_va_profile_integration.py
  tests/lambda_functions/va_profile/test_va_profile_remove_old_opt_outs.py
Labels: hotfix

#1644 #1523 Add additional environment variables to Perf for push notifications
  .talismanrc
  cd/application-deployment/perf/vaec-api-task-definition.json
  cd/application-deployment/perf/vaec-celery-task-definition.json
Labels: enhancement

#1649 Hotfix Cipher List
  app/va/mpi/mpi.py
  tests/app/complaint/test_complaint_rest.py
Labels: ignore-for-release

#1646 #1043 Add all VA public CA certificates to Docker image using VA HTTP server
  certs/VA-Internal-S2-ICA1-v1.cer
  certs/VA-Internal-S2-ICA10.cer
  certs/VA-Internal-S2-ICA11.cer
  certs/VA-Internal-S2-ICA12.cer
  certs/VA-Internal-S2-ICA13.cer
  certs/VA-Internal-S2-ICA14.cer
  certs/VA-Internal-S2-ICA15.cer
  certs/VA-Internal-S2-ICA16.cer
  certs/VA-Internal-S2-ICA17.cer
  certs/VA-Internal-S2-ICA18.cer
  certs/VA-Internal-S2-ICA19.cer
  certs/VA-Internal-S2-ICA2-v1.cer
  certs/VA-Internal-S2-ICA20.cer
  certs/VA-Internal-S2-ICA21.cer
  certs/VA-Internal-S2-ICA3-v1.cer
  certs/VA-Internal-S2-ICA4.cer
  certs/VA-Internal-S2-ICA5.cer
  certs/VA-Internal-S2-ICA6.cer
  certs/VA-Internal-S2-ICA7.cer
  certs/VA-Internal-S2-ICA8.cer
  certs/VA-Internal-S2-ICA9.cer
  certs/VA-Internal-S2-RCA1-v1.cer
  certs/VA-Internal-S2-RCA2.cer
  ci/Dockerfile
  scripts/import-va-certs.sh
Labels: enhancement

#1650 #1043 Revision for openssl
  ci/Dockerfile
Labels: bug

#1651 Update the issue template for a routine dependency upgrade.
  .github/ISSUE_TEMPLATE/notify-dependency-update-template.md
Labels: Tech Debt, Notify

#1638 # 1132 SQLAlchemy warnings after flask upgrade
  app/dao/inbound_sms_dao.py
  app/dao/notifications_dao.py
  app/models.py
  tests/README.md
Labels: bug

#1652 [Hotfix] Remove InvalidPhoneError From Automatic Retries
  Makefile
  app/celery/common.py
  app/celery/provider_tasks.py
  scripts/run_tests.sh
  tests/app/celery/test_provider_tasks.py
  tests/app/dao/test_fact_notification_status_dao.py
  tests/app/delivery/test_send_to_providers.py
Labels: bug, hotfix

#1659 Add Lambda Dependency Update Template
  .github/ISSUE_TEMPLATE/lambda-dependency-update-template.md
Labels: ignore-for-release

#1657 #1647 Dependency update
  .github/workflows/build.yml
  .github/workflows/db-downgrade.yml
  .github/workflows/deployment.yml
  .github/workflows/tests.yaml
  .github/workflows/twistlock.yml
  .github/workflows/update-datadog-image.yaml
  Makefile
  README.md
  requirements-app.txt
  requirements.txt
  tests/app/template_folder/test_template_folder_rest.py
Labels: dependencies

#1656 #1648 Update all remaining legacy SQL queries to use the new syntax
  .talismanrc
  app/dao/complaint_dao.py
  app/dao/fido2_key_dao.py
  app/dao/notifications_dao.py
  app/dao/organisation_dao.py
  app/dao/services_dao.py
  app/va/va_profile/va_profile_client.py
  tests/app/celery/test_ftp_update_tasks.py
  tests/app/celery/test_letters_pdf_tasks.py
  tests/app/celery/test_process_ses_receipts_tasks.py
  tests/app/celery/test_tasks.py
  tests/app/conftest.py
  tests/app/dao/test_api_key_dao.py
  tests/app/dao/test_communication_item_dao.py
  tests/app/dao/test_email_branding_dao.py
  tests/app/dao/test_events_dao.py
  tests/app/dao/test_fact_notification_status_dao.py
  tests/app/dao/test_fido2_keys_dao.py
  tests/app/dao/test_inbound_numbers_dao.py
  tests/app/dao/test_jobs_dao.py
  tests/app/dao/test_organisation_dao.py
  tests/app/dao/test_provider_details_dao.py
  tests/app/dao/test_service_callback_api_dao.py
  tests/app/dao/test_service_email_reply_to_dao.py
  tests/app/dao/test_service_letter_contact_dao.py
  tests/app/dao/test_service_sms_sender_dao.py
  tests/app/db.py
  tests/app/delivery/test_send_to_providers.py
  tests/app/email_branding/test_rest.py
  tests/app/invite/test_invite_rest.py
  tests/app/notifications/rest/test_send_notification.py
  tests/app/notifications/test_process_letter_notifications.py
  tests/app/notifications/test_process_notifications.py
  tests/app/notifications/test_receive_notification.py
  tests/app/organisation/test_invite_rest.py
  tests/app/organisation/test_rest.py
  tests/app/service/test_archived_service.py
  tests/app/service/test_callback_rest.py
  tests/app/service/test_rest.py
  tests/app/service/test_send_one_off_notification.py
  tests/app/service/test_service_data_retention_rest.py
  tests/app/service/test_service_whitelist.py
  tests/app/service/test_suspend_resume_service.py
  tests/app/template/test_rest.py
  tests/app/template_folder/test_template_folder_rest.py
  tests/app/test_schemas.py
  tests/app/user/test_rest.py
  tests/app/user/test_rest_verify.py
  tests/app/v2/notifications/test_post_letter_notifications.py
  tests/app/v2/notifications/test_post_notifications.py
  tests/app/va/va_profile/test_va_profile_client.py
  tests/lambda_functions/va_profile/test_va_profile_integration.py
Labels: Tech Debt

#1592 Updated README With New Requirements File Handling Instructions
  README.md
Labels: enhancement

#1669 #1374 deployment tracking
  .github/workflows/deployment.yml
  ci/Dockerfile.datadog
Labels: devops

#1672 Add Header Block so Template Shows in Zenhub
  .github/ISSUE_TEMPLATE/lambda-dependency-update-template.md
Labels: ignore-for-release
