Repository department-of-veterans-affairs/notification-api, pull requests merged in 2024-08, with the labels that each got.

#1889 #1770 Send All Email Statuses to VA Profile
  .github/pull_request_template.md
  .talismanrc
  app/__init__.py
  app/celery/process_ses_receipts_tasks.py
  app/config.py
  app/feature_flags.py
  app/va/va_profile/va_profile_client.py
  cd/application-deployment/dev/vaec-celery-task-definition.json
  cd/application-deployment/perf/vaec-celery-task-definition.json
  cd/application-deployment/prod/vaec-celery-task-definition.json
  cd/application-deployment/staging/vaec-celery-task-definition.json
  tests/app/celery/test_process_ses_receipts_tasks.py
  tests/app/va/va_profile/test_va_profile_client.py
Labels: enhancement

#1880 #1896 - Upgrade VAProfileClient to use v3 API endpoints
  .talismanrc
  app/celery/contact_information_tasks.py
  app/celery/lookup_recipient_communication_permissions_task.py
  app/va/va_profile/va_profile_client.py
  app/va/va_profile/va_profile_types.py
  cd/application-deployment/dev/vaec-celery-task-definition.json
  tests/app/va/va_profile/mock_response.json
  tests/app/va/va_profile/test_va_profile_v3.py
Labels: internal

#1899 Revert "#1896 - Upgrade VAProfileClient to use v3 API endpoints"
  .talismanrc
  app/celery/contact_information_tasks.py
  app/celery/lookup_recipient_communication_permissions_task.py
  app/va/va_profile/va_profile_client.py
  app/va/va_profile/va_profile_types.py
  cd/application-deployment/dev/vaec-celery-task-definition.json
  tests/app/va/va_profile/mock_response.json
  tests/app/va/va_profile/test_va_profile_v3.py
Labels: internal

#1904 Enable Comp Pen Flag in Prod
  cd/application-deployment/prod/vaec-celery-task-definition.json
  cd/application-deployment/staging/vaec-celery-task-definition.json
Labels: internal

#1901 #1897 - participant_id and va_profile_id in VAProfileLocalCache updated to BigInt
  app/models.py
  migrations/versions/0369a_va_profile_cache_fields.py
Labels: bug

#1911 Add pre-commit Dependency and Clean up Bandit Config
  .bandit.yml
  .pre-commit-config.yaml
  .talismanrc
  Makefile
  poetry.lock
  pyproject.toml
Labels: internal

#1917 Enable VA_PROFILE_V3_USE_PROFILE_API_V3 in staging, perf
  cd/application-deployment/perf/vaec-celery-task-definition.json
  cd/application-deployment/staging/vaec-celery-task-definition.json
Labels: internal

#1918 #1919 - Remove Old Feature Flag - CHECK_RECIPIENT_COMMUNICATION_PERMISSIONS_ENABLED
  app/feature_flags.py
  app/notifications/process_notifications.py
  cd/application-deployment/dev/vaec-api-task-definition.json
  cd/application-deployment/dev/vaec-celery-beat-task-definition.json
  cd/application-deployment/dev/vaec-celery-task-definition.json
  cd/application-deployment/perf/vaec-api-task-definition.json
  cd/application-deployment/perf/vaec-celery-beat-task-definition.json
  cd/application-deployment/perf/vaec-celery-task-definition.json
  cd/application-deployment/prod/vaec-api-task-definition.json
  cd/application-deployment/prod/vaec-celery-beat-task-definition.json
  cd/application-deployment/prod/vaec-celery-task-definition.json
  cd/application-deployment/staging/vaec-api-task-definition.json
  cd/application-deployment/staging/vaec-celery-beat-task-definition.json
  cd/application-deployment/staging/vaec-celery-task-definition.json
Labels: internal

#1921 #1920 - enable feature flag VA_PROFILE_V3_USE_PROFILE_API_V3 in production
  cd/application-deployment/prod/vaec-celery-task-definition.json
Labels: internal

#1898 #1800 Delivery Status Callbacks: VA Profile lookup failures
  app/celery/common.py
  app/celery/contact_information_tasks.py
  app/celery/lookup_va_profile_id_task.py
  app/celery/service_callback_tasks.py
  tests/app/celery/test_contact_information_tasks.py
  tests/app/celery/test_lookup_va_profile_id_task.py
Labels: bug

#1922 Revert "#1800 Delivery Status Callbacks: VA Profile lookup failures"
  app/celery/common.py
  app/celery/contact_information_tasks.py
  app/celery/lookup_va_profile_id_task.py
  app/celery/service_callback_tasks.py
  tests/app/celery/test_contact_information_tasks.py
  tests/app/celery/test_lookup_va_profile_id_task.py
Labels: internal

#1924 #1874 exception logging
  app/attachments/store.py
  app/callback/sqs_client.py
  app/clients/sms/twilio.py
  app/cronitor.py
  app/dao/dao_utils.py
  app/dao/notifications_dao.py
  app/dao/services_dao.py
  app/delivery/send_to_providers.py
  app/errors.py
  app/googleanalytics/ga4.py
  app/integrations/comp_and_pen/scheduled_message_helpers.py
  app/mobile_app/mobile_app_registry.py
  app/notifications/aws_sns_status_callback.py
  app/notifications/notifications_govdelivery_callback.py
  app/notifications/notifications_ses_callback.py
  app/notifications/send_notifications.py
  app/notifications/utils.py
  app/oauth/rest.py
  app/service/whitelist_rest.py
  app/status/redis_check.py
  app/user/rest.py
  app/v2/errors.py
  app/va/va_profile/va_profile_client.py
  app/va/vetext/client.py
  tests/app/mobile_app/test_mobile_app_registry.py
  tests/app/notifications/test_send_notifications.py
  tests/app/va/vetext/test_client.py
Labels: internal

#1923 #1925- Remove feature flag VA_PROFILE_V3_USE_PROFILE_API_V3 and code cleanup
  .talismanrc
  app/celery/contact_information_tasks.py
  app/celery/lookup_recipient_communication_permissions_task.py
  app/feature_flags.py
  app/models.py
  app/va/va_profile/exceptions.py
  app/va/va_profile/va_profile_client.py
  cd/application-deployment/dev/vaec-celery-task-definition.json
  cd/application-deployment/perf/vaec-celery-task-definition.json
  cd/application-deployment/prod/vaec-celery-task-definition.json
  cd/application-deployment/staging/vaec-celery-task-definition.json
  tests/app/celery/test_contact_information_tasks.py
  tests/app/celery/test_lookup_recipient_communication_permissions_task.py
  tests/app/va/va_profile/mock_response.json
  tests/app/va/va_profile/test_va_profile_client.py
  tests/app/va/va_profile/test_va_profile_v3.py
Labels: internal

#1932 HOTFIX - Ignore dependency vulnerability Gunicorn 22.0.0
  Makefile
Labels: ignore-for-release

#1934 HOTFIX - GHA "environment" Variable Pruning
  .github/workflows/deployment.yml
  .github/workflows/dev_deploy.yml
Labels: ignore-for-release

#1935 #1779 Enable VA Profile Email Status Sends in Perf & Staging
  cd/application-deployment/perf/vaec-celery-task-definition.json
  cd/application-deployment/staging/vaec-celery-task-definition.json
Labels: internal

#1939 HOTFIX - Log Replay Notification IDs
  app/celery/process_ses_receipts_tasks.py
  app/celery/scheduled_tasks.py
Labels: internal

#1943 #1711 - Remove unnecessary secret keys from task definitions
  app/config.py
  cd/application-deployment/dev/vaec-api-task-definition.json
  cd/application-deployment/dev/vaec-celery-task-definition.json
  cd/application-deployment/perf/vaec-api-task-definition.json
  cd/application-deployment/perf/vaec-celery-task-definition.json
  cd/application-deployment/prod/vaec-api-task-definition.json
  cd/application-deployment/prod/vaec-celery-task-definition.json
  cd/application-deployment/staging/vaec-api-task-definition.json
  cd/application-deployment/staging/vaec-celery-task-definition.json
Labels: internal

#1946 UTILS-152 Add Action Link Formatting to Email Templates
  .talismanrc
  poetry.lock
Labels: enhancement

#1949 #1905 - Rename master to main in Github Workflows and Docs
  .github/ISSUE_TEMPLATE/notify-dependency-update-template.md
  .github/pull_request_template.md
  .github/scripts/trigger-regression.js
  .github/workflows/build.yml
  .github/workflows/cd-pipeline.yml
  .github/workflows/deploy-release.yml
  .github/workflows/deploy_lambda_dev.yml
  .github/workflows/deployment.yml
  .github/workflows/dev_deploy.yml
  .github/workflows/lambda-functions.yml
  .github/workflows/load-test-email-delivery-time.yaml
  .github/workflows/load-test-sms-response-time.yaml
  .github/workflows/test-github-actions.yml
  .github/workflows/tests.yaml
  .github/workflows/update-datadog-image.yaml
  README.md
  app/clients/sms/twilio.py
  documents/cds-to-va-changes.md
Labels: internal

#1954 #1933 - Regular Update For Dependencies
  .github/workflows/deployment.yml
  .talismanrc
  Makefile
  poetry.lock
Labels: internal

#1956 #1933 - Update boto3 dependency in requirement.txt files
  load_testing/requirements.txt
  load_testing/requirements_cli.txt
Labels: internal

#1958 UTILS-127 Bug: Update notification-utils for Email Preview Exposes HTML Tags
  .talismanrc
  poetry.lock
Labels: bug

#1961 #1895 Provider Service log level
  app/provider_details/provider_service.py
Labels: bug

#1973 #1963 - Remove Eventlet Gunicorn Worker
  .talismanrc
  gunicorn_config.py
  poetry.lock
  pyproject.toml
Labels: bug
