Repository department-of-veterans-affairs/notification-api, pull requests merged in 2024-01, with the labels that each got.

#1581 #1525 [BUGFIX] KeyError Invalid Phone Number Prefix
  app/notifications/validators.py
  tests/app/notifications/test_validators.py
Labels: bug

#1583 HOTFIX - Cleaned Loggers and Exceptions
  app/celery/service_callback_tasks.py
  app/va/va_profile/va_profile_client.py
  app/va/vetext/client.py
  lambda_functions/two_way_sms/two_way_sms_v2.py
  lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
  tests/app/va/vetext/test_client.py
Labels: hotfix

#1589 [BUG] cachetools Local Requirements
  requirements-app.txt
Labels: bug

#1573 #1538 SQLAlchemy Query Updates
  .talismanrc
  app/celery/nightly_tasks.py
  app/celery/process_delivery_status_result_tasks.py
  app/celery/scheduled_tasks.py
  app/commands.py
  app/communication_item/rest.py
  app/dao/__init__.py
  app/dao/annual_billing_dao.py
  app/dao/api_key_dao.py
  app/dao/communication_item_dao.py
  app/dao/complaint_dao.py
  app/dao/daily_sorted_letter_dao.py
  app/dao/dao_utils.py
  app/dao/email_branding_dao.py
  app/dao/fact_billing_dao.py
  app/dao/fact_notification_status_dao.py
  app/dao/inbound_numbers_dao.py
  app/dao/inbound_sms_dao.py
  app/dao/invited_org_user_dao.py
  app/dao/invited_user_dao.py
  app/dao/jobs_dao.py
  app/dao/login_event_dao.py
  app/dao/notifications_dao.py
  app/dao/organisation_dao.py
  app/dao/permissions_dao.py
  app/dao/provider_details_dao.py
  app/dao/provider_rates_dao.py
  app/dao/service_callback_api_dao.py
  app/dao/service_callback_dao.py
  app/dao/service_data_retention_dao.py
  app/dao/service_email_reply_to_dao.py
  app/dao/service_letter_contact_dao.py
  app/dao/service_permissions_dao.py
  app/dao/service_sms_sender_dao.py
  app/dao/service_user_dao.py
  app/dao/service_whitelist_dao.py
  app/dao/services_dao.py
  app/dao/template_folder_dao.py
  app/dao/templates_dao.py
  app/dao/users_dao.py
  app/invite/rest.py
  app/model/user.py
  app/organisation/rest.py
  app/service/rest.py
  app/user/rest.py
  scripts/run_tests.sh
  tests/app/communication_item/test_rest.py
  tests/app/dao/notification_dao/test_notification_dao.py
  tests/app/dao/test_annual_billing_dao.py
  tests/app/dao/test_complaint_dao.py
  tests/app/dao/test_fact_notification_status_dao.py
  tests/app/dao/test_ft_billing_dao.py
  tests/app/dao/test_invited_user_dao.py
  tests/app/dao/test_provider_rates_dao.py
  tests/app/dao/test_template_folder_dao.py
  tests/app/dao/test_users_dao.py
  tests/app/status/test_status.py
  tests/lambda_functions/delivery_status_processor_lambda/test_delivery_status_processor_lambda.py
  tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
Labels: Tech Debt, enhancement

#1591 Local Env Docker Update
  ci/Dockerfile.local
Labels: enhancement

#1587 #1553 Update Lambda Dependencies
  .github/workflows/lambda-functions.yml
  lambda_functions/delivery_status_processor_lambda/requirements-lambda.txt
  lambda_functions/nightly_billing_bigquery_upload/requirements-lambda.txt
  lambda_functions/nightly_stats_bigquery_upload/requirements-lambda.txt
  lambda_functions/readme.md
  lambda_functions/two_way_sms/requirements-lambda.txt
  lambda_functions/va_profile/requirements-lambda.txt
  lambda_functions/va_profile_remove_old_opt_outs/requirements-lambda.txt
  lambda_functions/vetext_incoming_forwarder_lambda/requirements-lambda.txt
  requirements_for_test.txt
Labels: dependencies

#1565 #1526 Automate Regression on Deploy
  .github/scripts/trigger-regression.js
  .github/workflows/dev_deploy.yml
  .github/workflows/prerelease_trigger.yml
  .github/workflows/regression-public.yml
  .github/workflows/run-regression.yml
  .github/workflows/tag_trigger.yml
Labels: github_actions, enhancement, devops

#1610 #1526 - hotfix for environment type
  .github/workflows/run-regression.yml
Labels: hotfix

#1612 #1526 - bug fix for prerelease job dependency
  .github/workflows/prerelease_trigger.yml
Labels: bug

#1609 [HOTFIX] VEText Identify RequestException
  app/va/vetext/client.py
Labels: hotfix

#1597 [HOTFIX] Updated CPU Values
  cd/application-deployment/dev/vaec-api-task-definition.json
  cd/application-deployment/perf/vaec-api-task-definition.json
  cd/application-deployment/prod/vaec-api-task-definition.json
  cd/application-deployment/staging/vaec-api-task-definition.json
Labels: hotfix

#1607 #1539 - Client Postman Collection
  .talismanrc
  documents/postman/README.md
  documents/postman/internal_api_developers/README.md
  documents/postman/internal_api_developers/development.postman_environment.json
  documents/postman/internal_api_developers/notification-api.postman_collection.json
  documents/postman/internal_api_developers/performance.postman_environment.json
  documents/postman/internal_api_developers/staging.postman_environment.json
  documents/postman/notification-api-simplified.postman_collection.json
  documents/postman/staging-simplified.postman_environment.json
Labels: enhancement

#1621 #1501 [v3] Removed Extra Decorator
  app/celery/v3/notification_tasks.py
  requirements_for_test.txt
  tests/app/communication_item/test_rest.py
  tests/app/test_cronitor.py
Labels: bug

#1623 Update Readme Postman Link
  README.md
Labels: ignore-for-release
