Repository department-of-veterans-affairs/notification-api, pull requests merged in 2025-03, with the labels that each got.

#2338 #2207 - Add notification portal tasks to task definition cleanup
  .github/workflows/task-defnition-cleanup.yaml
Labels: patch

#2339 #803 - Handle NotificationHistory in SES Complaint Response
  app/celery/process_ses_receipts_tasks.py
  app/celery/service_callback_tasks.py
  tests/app/celery/test_process_ses_receipts_tasks.py
Labels: patch

#2347 UTILS-201 Add headers 4-6 for Portal
  .talismanrc
  poetry.lock
Labels: patch

#2348 #803 - Hotfix - resolve unbound variable and exception handling
  app/celery/process_ses_receipts_tasks.py
  app/notifications/notifications_ses_callback.py
  tests/app/celery/test_process_ses_receipts_tasks.py
  tests/app/conftest.py
  tests/app/notifications/test_notifications_ses_callback.py
Labels: patch

#2346 #2311 - API Key Revoked Filter
  .talismanrc
  app/dao/api_key_dao.py
  app/service/rest.py
  documents/openapi/openapi.yaml
  tests/app/dao/test_api_key_dao.py
  tests/app/service/test_api_key_endpoints.py
Labels: minor

#2351 #2311 - Postman update for api keys
  .talismanrc
  documents/openapi/openapi.yaml
  documents/postman/internal_api_developers/notification-api.postman_collection.json
Labels: patch

#2350 TEAM-1487 - Code scan
  README.md
  app/internal/rest.py
  tests/app/internal/test_rest.py
Labels: patch

#2349 HOTFIX - Removed session-based Tests
  .gitignore
  tests/app/service/test_sender.py
Labels: patch

#2365 HOTFIX - Ensured status_reason was Bounce
  app/celery/process_ses_receipts_tasks.py
Labels: hotfix

#2361 #1042 - Merge Nightly Stats Lambdas
  .github/workflows/deploy_lambda_dev.yml
  .github/workflows/lambda-functions.yml
  .talismanrc
  app/celery/reporting_tasks.py
  app/config.py
  app/va/va_profile/va_profile_client.py
  lambda_functions/nightly_billing_bigquery_upload/nightly_billing_stats_upload_lambda.py
  lambda_functions/nightly_stats_bigquery_upload/nightly_stats_bigquery_upload_lambda.py
  tests/app/celery/test_reporting_tasks.py
  tests/lambda_functions/nightly_stats_bigquery_upload/test_nightly_lambda.py
  tests/lambda_functions/nightly_stats_bigquery_upload/test_nightly_stats_bigquery_upload.py
Labels: patch

#2369 HOT FIX - Update Alembic and Setuptools
  .talismanrc
  poetry.lock
  pyproject.toml
  tests/app/notifications/test_process_notifications.py
Labels: patch

#2368 #2366 - Ensure No Duplicate Emails
  app/celery/process_ses_receipts_tasks.py
  app/celery/provider_tasks.py
  app/delivery/send_to_providers.py
  tests/app/celery/test_process_ses_receipts_tasks.py
  tests/app/celery/test_provider_tasks.py
  tests/app/delivery/test_send_to_providers.py
Labels: patch

#2374 Hotfix 1042 - Merge Stats Lambdas
  .talismanrc
  app/celery/reporting_tasks.py
  app/config.py
  cd/application-deployment/dev/dev.env
  cd/application-deployment/perf/perf.env
  cd/application-deployment/prod/prod.env
  cd/application-deployment/staging/staging.env
  lambda_functions/nightly_stats_bigquery_upload/nightly_stats_bigquery_upload_lambda.py
  tests/app/celery/test_reporting_tasks.py
  tests/lambda_functions/nightly_stats_bigquery_upload/test_nightly_lambda.py
Labels: patch
